// silkgen converts a designer-produced .silkui file into a Go source
// snippet using silk/decl's builder DSL. Wraps the snippet in a
// minimal Go file with package + imports + a build function so the
// output is drop-in compilable.
//
// Usage:
//
//	silkgen path/to/main.silkui                # writes to stdout
//	silkgen -o gen.silk.go path/to/main.silkui  # writes to a file
//	silkgen -package mypkg main.silkui          # custom package name
//	silkgen -func BuildMain main.silkui         # custom function name
//
// The output skeleton:
//
//	// Code generated by silkgen — DO NOT EDIT.
//	package <package>
//
//	import "silk/decl"
//
//	func <Func>() *decl.Node {
//	    return decl.Form(...)
//	}
//
// Re-running silkgen on the same .silkui yields byte-identical output
// (subject to gofmt). This makes the tool safe to wire into go:generate
// directives.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"silk/core"
	"silk/decl"
)

func main() {
	var (
		outFile     = flag.String("o", "", "write output to file (default stdout)")
		packageName = flag.String("package", "ui", "package name in the generated file")
		funcName    = flag.String("func", "", "function name (default Build<Stem> derived from input filename)")
	)
	flag.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: silkgen [-o out.go] [-package P] [-func F] input.silkui")
		flag.PrintDefaults()
	}
	flag.Parse()
	if flag.NArg() != 1 {
		flag.Usage()
		os.Exit(2)
	}
	in := flag.Arg(0)

	// Auto-derive function name from input stem when -func not given.
	// "main.silkui" → "BuildMain"; "Editor.silkui" → "BuildEditor".
	derivedFunc := *funcName
	if derivedFunc == "" {
		base := filepath.Base(in)
		stem := strings.TrimSuffix(base, filepath.Ext(base))
		derivedFunc = "Build" + capitalise(stem)
	}

	// Load the .silkui via core's TDoc parser, then convert to AST.
	doc, err := core.LoadTDocFile(in)
	if err != nil {
		fail("read %s: %v", in, err)
	}
	tree, err := decl.FromTDoc(doc)
	if err != nil {
		fail("parse %s: %v", in, err)
	}
	body := decl.ToGo(tree)

	src := fmt.Sprintf(`// Code generated by silkgen — DO NOT EDIT.
// Source: %s

package %s

import "silk/decl"

// %s constructs the widget tree decoded from %s. Pair with
// (*decl.Node).Build() at runtime to materialise the actual widgets.
func %s() *decl.Node {
	return %s
}
`, filepath.Base(in), *packageName, derivedFunc, filepath.Base(in), derivedFunc, body)

	if *outFile == "" {
		os.Stdout.WriteString(src)
		return
	}
	if err := os.WriteFile(*outFile, []byte(src), 0644); err != nil {
		fail("write %s: %v", *outFile, err)
	}
}

// capitalise upper-cases the first byte if it's a lowercase ASCII
// letter; non-ASCII / non-letter prefixes pass through. Sufficient
// for filename-derived identifiers; full Unicode title-casing isn't
// worth the dependency.
func capitalise(s string) string {
	if s == "" {
		return s
	}
	c := s[0]
	if c >= 'a' && c <= 'z' {
		return string(c-32) + s[1:]
	}
	return s
}

func fail(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "silkgen: "+format+"\n", args...)
	os.Exit(1)
}
