package buildissues

import (
	"reflect"
	"strings"
	"testing"
)

func TestSeverityString(t *testing.T) {
	cases := []struct {
		sev  Severity
		want string
	}{
		{Error, "error"},
		{Warning, "warning"},
		{Info, "info"},
		{Severity(99), "unknown"},
	}
	for _, c := range cases {
		if got := c.sev.String(); got != c.want {
			t.Errorf("Severity(%d).String() = %q, want %q", int(c.sev), got, c.want)
		}
	}
}

func TestParseSingleLine(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want Issue
	}{
		{
			name: "compiler error with column",
			in:   "./main.go:10:6: undefined: foo",
			want: Issue{File: "./main.go", Line: 10, Col: 6, Severity: Error, Message: "undefined: foo"},
		},
		{
			name: "error without column",
			in:   "./main.go:20: syntax error: unexpected }",
			want: Issue{File: "./main.go", Line: 20, Col: 0, Severity: Error, Message: "syntax error: unexpected }"},
		},
		{
			name: "vet warning classified by warning: keyword",
			in:   "./main.go:8:2: warning: unreachable code",
			want: Issue{File: "./main.go", Line: 8, Col: 2, Severity: Warning, Message: "warning: unreachable code"},
		},
		{
			name: "message with many colons keeps full message after location",
			in:   "./a.go:1:2: cannot use x (type A) as type B: mismatch: detail",
			want: Issue{File: "./a.go", Line: 1, Col: 2, Severity: Error, Message: "cannot use x (type A) as type B: mismatch: detail"},
		},
		{
			name: "windows path with column",
			in:   `C:\src\a.go:3:2: x`,
			want: Issue{File: `C:\src\a.go`, Line: 3, Col: 2, Severity: Error, Message: "x"},
		},
		{
			name: "windows path without column",
			in:   `C:\src\a.go:7: bad thing`,
			want: Issue{File: `C:\src\a.go`, Line: 7, Col: 0, Severity: Error, Message: "bad thing"},
		},
		{
			name: "indented go test failure detail",
			in:   "    foo_test.go:12: got 1, want 2",
			want: Issue{File: "foo_test.go", Line: 12, Col: 0, Severity: Error, Message: "got 1, want 2"},
		},
		{
			name: "unicode file and message",
			in:   "文件.go:5:3: 未使用的变量: x",
			want: Issue{File: "文件.go", Line: 5, Col: 3, Severity: Error, Message: "未使用的变量: x"},
		},
		{
			name: "multi-dot filename",
			in:   "pkg/a.b.go:9:9: oops",
			want: Issue{File: "pkg/a.b.go", Line: 9, Col: 9, Severity: Error, Message: "oops"},
		},
		{
			name: "trailing whitespace trimmed from message",
			in:   "a.go:1:1: spaced   ",
			want: Issue{File: "a.go", Line: 1, Col: 1, Severity: Error, Message: "spaced"},
		},
		{
			name: "carriage return line ending stripped",
			in:   "a.go:2:2: crlf msg\r",
			want: Issue{File: "a.go", Line: 2, Col: 2, Severity: Error, Message: "crlf msg"},
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := Parse(c.in)
			if len(got) != 1 {
				t.Fatalf("Parse(%q) returned %d issues, want 1: %+v", c.in, len(got), got)
			}
			if !reflect.DeepEqual(got[0], c.want) {
				t.Errorf("Parse(%q)[0] = %+v, want %+v", c.in, got[0], c.want)
			}
		})
	}
}

func TestParseIgnoresNonIssues(t *testing.T) {
	cases := []struct {
		name string
		in   string
	}{
		{"empty", ""},
		{"blank lines", "\n   \n\t\n"},
		{"package header", "# github.com/x/y"},
		{"package header with test suffix", "# github.com/x/y [github.com/x/y.test]"},
		{"ok line", "ok  \tgithub.com/x/y\t0.123s"},
		{"no test files", "?   \tgithub.com/x/y\t[no test files]"},
		{"run header", "=== RUN   TestFoo"},
		{"fail header", "--- FAIL: TestFoo (0.00s)"},
		{"pass word", "PASS"},
		{"fail summary", "FAIL\tgithub.com/x/y\t0.012s"},
		{"exit status", "exit status 1"},
		{"panic message", "panic: runtime error: index out of range [3] with length 2"},
		{"stack frame with file:line but no colon-space", "\t/usr/local/go/src/runtime/panic.go:914 +0x21a"},
		{"goroutine header", "goroutine 1 [running]:"},
		{"timestamp line", "2026-07-08T12:34:56: starting up"},
		{"millisecond timestamp", "12:34:56.789: tick"},
		{"extensionless pseudo location", "<autogenerated>:1: something"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := Parse(c.in); len(got) != 0 {
				t.Errorf("Parse(%q) = %+v, want no issues", c.in, got)
			}
		})
	}
}

func TestParsePackageLineSkippedButDiagnosticsKept(t *testing.T) {
	in := "# github.com/uk0/silk/buildissues\n" +
		"./buildissues.go:5:2: imported and not used: \"fmt\"\n" +
		"./buildissues.go:12:6: undefined: bar\n"
	want := []Issue{
		{File: "./buildissues.go", Line: 5, Col: 2, Severity: Error, Message: `imported and not used: "fmt"`},
		{File: "./buildissues.go", Line: 12, Col: 6, Severity: Error, Message: "undefined: bar"},
	}
	got := Parse(in)
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Parse(...) = %+v, want %+v", got, want)
	}
}

func TestParseGoTestBlockOneIssuePerDiagnostic(t *testing.T) {
	in := strings.Join([]string{
		"=== RUN   TestParse",
		"--- FAIL: TestParse (0.00s)",
		"    buildissues_test.go:42: got 0 issues, want 1",
		"    buildissues_test.go:50: mismatch: field File",
		"FAIL",
		"exit status 1",
		"FAIL\tgithub.com/uk0/silk/buildissues\t0.012s",
	}, "\n")
	want := []Issue{
		{File: "buildissues_test.go", Line: 42, Col: 0, Severity: Error, Message: "got 0 issues, want 1"},
		{File: "buildissues_test.go", Line: 50, Col: 0, Severity: Error, Message: "mismatch: field File"},
	}
	got := Parse(in)
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Parse(go test block) = %+v, want %+v", got, want)
	}
}

func TestParseMixedBuildBlock(t *testing.T) {
	in := strings.Join([]string{
		"# github.com/x/y",
		"./main.go:10:6: undefined: foo",
		"",
		"./util.go:3: cannot find package: \"x/z\"",
		"./cgo.go:7:1: warning: implicit declaration of function 'bar'",
		"ok  \tgithub.com/x/y\t0.5s",
	}, "\n")
	want := []Issue{
		{File: "./main.go", Line: 10, Col: 6, Severity: Error, Message: "undefined: foo"},
		{File: "./util.go", Line: 3, Col: 0, Severity: Error, Message: `cannot find package: "x/z"`},
		{File: "./cgo.go", Line: 7, Col: 1, Severity: Warning, Message: "warning: implicit declaration of function 'bar'"},
	}
	got := Parse(in)
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Parse(mixed) = %+v, want %+v", got, want)
	}
}

func TestParseEmptyReturnsNil(t *testing.T) {
	if got := Parse(""); got != nil {
		t.Errorf("Parse(\"\") = %+v, want nil", got)
	}
}

func TestParseLargeInput(t *testing.T) {
	var b strings.Builder
	const n = 5000
	for i := 0; i < n; i++ {
		b.WriteString("=== RUN   TestX\n")   // noise, skipped
		b.WriteString("./big.go:1:1: boom\n") // real diagnostic
	}
	got := Parse(b.String())
	if len(got) != n {
		t.Fatalf("Parse(large) returned %d issues, want %d", len(got), n)
	}
	if got[0] != (Issue{File: "./big.go", Line: 1, Col: 1, Severity: Error, Message: "boom"}) {
		t.Errorf("first issue = %+v, want ./big.go:1:1 boom", got[0])
	}
}

func TestParseLongSingleLine(t *testing.T) {
	msg := strings.Repeat("x", 200000)
	got := Parse("./huge.go:1:1: " + msg)
	if len(got) != 1 {
		t.Fatalf("Parse(long line) returned %d issues, want 1", len(got))
	}
	if got[0].Message != msg {
		t.Errorf("long message length = %d, want %d", len(got[0].Message), len(msg))
	}
}
