// Package buildissues parses the textual output of the Go toolchain
// (go build, go vet, go test) into structured issues suitable for an
// Issues pane. It is UI-agnostic and depends only on the standard library.
package buildissues

import (
	"bufio"
	"regexp"
	"strconv"
	"strings"
)

// Severity classifies how serious an Issue is.
type Severity int

const (
	// Error is a compiler or go vet diagnostic (the default classification).
	Error Severity = iota
	// Warning is a non-fatal diagnostic, e.g. a cgo/C compiler "warning:".
	Warning
	// Info is a purely informational note.
	Info
)

// String returns the lowercase name of the severity.
func (s Severity) String() string {
	switch s {
	case Error:
		return "error"
	case Warning:
		return "warning"
	case Info:
		return "info"
	default:
		return "unknown"
	}
}

// Issue is a single diagnostic located at File:Line[:Col]. Col is 0 when the
// tool reported no column.
type Issue struct {
	File     string
	Line     int
	Col      int
	Severity Severity
	Message  string
}

// locRe matches a leading "file:line[:col]: message" location prefix.
//
//   - The file group (.+?\.\w+) is non-greedy and must end in a ".ext", so the
//     FIRST valid "<file.ext>:line[:col]: " triplet wins and the rest of the
//     line (including any further colons) stays in the message. Requiring an
//     extension keeps a bare "hh:mm:ss: " timestamp — which has no leading
//     "file.ext" — from being mistaken for a location, while the non-greedy
//     match steps safely over a Windows drive letter ("C:\...").
//   - The column group is optional (":line" alone yields Col 0).
//   - The message is separated by ":" plus at least one whitespace char. That
//     mandatory colon-then-space is what distinguishes a real location from a
//     goroutine stack-trace frame ("file.go:10 +0x20", no colon after the line)
//     or an "hh:mm:ss" timestamp (no whitespace after the final colon).
var locRe = regexp.MustCompile(`^(.+?\.\w+):(\d+)(?::(\d+))?:\s+(.*)$`)

// Parse scans tool output and returns one Issue per recognized diagnostic
// line, in source order. It returns nil when there are no issues.
//
// Recognized: any line whose whitespace-trimmed form begins with a
// "file.ext:line: msg" or "file.ext:line:col: msg" location prefix. This covers
// compiler errors, go vet reports, and the indented "file:line: msg" details
// that go test prints beneath a "--- FAIL" header.
//
// Ignored (kept out of the result): blank lines; package-context headers
// beginning with "# " (e.g. "# github.com/x/y"); test-runner status lines such
// as "ok  pkg", "--- FAIL", "=== RUN", "PASS", "FAIL"; panic messages; and
// goroutine stack-trace frames ("file.go:10 +0x20") — none carry a
// "file.ext:line[:col]: " prefix, so they never match. Pseudo-locations without
// an extension (e.g. "<autogenerated>:1:") are likewise treated as non-issues.
//
// Severity: a diagnostic whose message contains "warning:" is a Warning; every
// other recognized diagnostic is an Error.
func Parse(output string) []Issue {
	var issues []Issue
	scanner := bufio.NewScanner(strings.NewReader(output))
	// Raise the per-line limit well above the default 64 KiB so a very large
	// single line is not truncated.
	scanner.Buffer(make([]byte, 0, 64*1024), 16*1024*1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "# ") {
			continue
		}
		m := locRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		lineNo, _ := strconv.Atoi(m[2]) // m[2] is \d+; Atoi cannot fail.
		col := 0
		if m[3] != "" {
			col, _ = strconv.Atoi(m[3])
		}
		msg := strings.TrimSpace(m[4])
		issues = append(issues, Issue{
			File:     m[1],
			Line:     lineNo,
			Col:      col,
			Severity: classify(msg),
			Message:  msg,
		})
	}
	return issues
}

// classify chooses a Severity from a diagnostic message.
func classify(message string) Severity {
	if strings.Contains(strings.ToLower(message), "warning:") {
		return Warning
	}
	return Error
}
