package ged

import (
	"fmt"
	"go/format"

	"github.com/uk0/silk/decl"
)

// GenerateDeclCode produces a complete .silk.go file using the silk/decl
// builder DSL. Functionally a sibling of GenerateCode — the difference is
// the *style* of output:
//
//   - GenerateCode produces an imperative struct + constructor:
//
//     type MyAppUI struct {
//     Form *gui.Form
//     BtnOK *gui.Button
//     }
//     func NewMyAppUI() *MyAppUI { ... }
//
//   - GenerateDeclCode produces a declarative builder expression:
//
//     func BuildMyApp() *decl.Node {
//     return decl.Form(decl.P("title", "MyApp"),
//     decl.Children(
//     decl.Button(decl.ID("btnOK"), decl.P("text", "OK")),
//     ),
//     )
//     }
//
// The decl form pairs with (*decl.Node).Build() at runtime to materialise
// the actual widgets. It's the same shape silkgen emits from a .silkui
// file — wiring the designer through this entry point closes the loop:
// designer → AST → decl Go source → runtime widgets, all in-process.
//
// Event-handler code (FakeWidget.GetCode()) is NOT inlined; the decl AST
// has no built-in slot for raw Go bodies. Handlers are emitted as
// trailing comments so the user can transcribe them or wire them via a
// host file. The imperative GenerateCode path remains the right choice
// when the form needs first-class handler bodies in the same file.
func (scene *GedScene) GenerateDeclCode(opts CodeGenOptions) string {
	if opts.PackageName == "" {
		opts.PackageName = "ui"
	}
	typeStem := opts.TypeName
	if typeStem == "" {
		typeStem = sanitizeIdentifier(scene.FormTitle())
		if typeStem == "" {
			typeStem = "Form"
		}
	}
	funcName := "Build" + typeStem

	root := buildSceneDeclNode(scene)
	body := decl.ToGo(root)

	// Collect any handler code as a footer; the decl AST has no native
	// place for raw Go bodies so we surface them as comments to keep the
	// designer-authored intent visible.
	handlers := collectHandlerComments(scene)

	src := fmt.Sprintf(`// Code generated by Silk Designer Editor (decl mode). DO NOT EDIT.

package %s

import "github.com/uk0/silk/decl"

// %s constructs the widget tree designed in the editor. Pair with
// (*decl.Node).Build() at runtime to materialise the actual widgets.
func %s() *decl.Node {
	return %s
}
%s`, opts.PackageName, funcName, funcName, body, handlers)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Format failure means the body assembly is malformed; surface
		// the raw text rather than crash so the user can still inspect.
		return src
	}
	return string(formatted)
}

// buildSceneDeclNode walks the scene to produce a decl.Form root node
// carrying every FakeWidget child as a decl child node.
func buildSceneDeclNode(scene *GedScene) *decl.Node {
	formW := roundPx(scene.Width())
	formH := roundPx(scene.Height())

	root := decl.Form(
		decl.P("title", scene.FormTitle()),
		decl.P("width", formW),
		decl.P("height", formH),
	)

	for _, c := range scene.Children() {
		fake, ok := c.(*FakeWidget)
		if !ok {
			continue
		}
		root.Children = append(root.Children, buildFakeDeclNode(fake))
	}
	return root
}

// buildFakeDeclNode converts one FakeWidget into a decl.Node. Geometry
// (x/y/width/height) is always written in roundPx form so the
// designer's pixel grid lines up with what the runtime sees. A non-empty
// WidgetName becomes the node ID — that's how the designer cross-
// references widgets between layout and event-handler scopes.
func buildFakeDeclNode(fake *FakeWidget) *decl.Node {
	n := &decl.Node{
		Type: fake.WidgetFactoryName(),
		ID:   fake.WidgetName(),
	}
	n.SetProp("x", decl.Lit{V: roundPx(fake.X())})
	n.SetProp("y", decl.Lit{V: roundPx(fake.Y())})
	n.SetProp("width", decl.Lit{V: roundPx(fake.Width())})
	n.SetProp("height", decl.Lit{V: roundPx(fake.Height())})

	if w := fake.Widget(); w != nil {
		if t, ok := w.(interface{ Text() string }); ok {
			if text := t.Text(); text != "" {
				n.SetProp("text", decl.Lit{V: text})
			}
		} else if t, ok := w.(interface{ Title() string }); ok {
			if title := t.Title(); title != "" {
				n.SetProp("title", decl.Lit{V: title})
			}
		}
	}

	// Recurse into nested children so a container widget (VBox/HBox/...)
	// emits its laid-out widgets as decl child nodes, mirroring the
	// designer's tree. Flat widgets have no children and add nothing.
	for _, c := range fake.Children() {
		if child, ok := c.(*FakeWidget); ok {
			n.Children = append(n.Children, buildFakeDeclNode(child))
		}
	}
	return n
}

// collectHandlerComments returns a footer comment block listing every
// FakeWidget that has hand-authored event-handler code. Empty string
// when no scene child has a code body, so the generated file ends
// cleanly. This is intentionally a comment block, not real Go: the
// decl path is for structure-only output and host code is expected to
// register handlers separately.
func collectHandlerComments(scene *GedScene) string {
	var has bool
	var out string
	for _, c := range scene.Children() {
		fake, ok := c.(*FakeWidget)
		if !ok {
			continue
		}
		code := fake.GetCode()
		if code == "" {
			continue
		}
		if !has {
			out += "\n// Event handlers (designer-authored — wire these in your host file):\n//\n"
			has = true
		}
		name := fake.WidgetName()
		if name == "" {
			name = fake.WidgetFactoryName()
		}
		out += fmt.Sprintf("//   %s:\n", name)
		// Indent the body so it reads as a comment block.
		for _, line := range splitLines(code) {
			out += "//     " + line + "\n"
		}
	}
	return out
}

// splitLines is a small helper that splits a code string on '\n' without
// dropping empty intermediate lines. Avoids pulling strings.Split for
// the single use site here.
func splitLines(s string) []string {
	var out []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			out = append(out, s[start:i])
			start = i + 1
		}
	}
	out = append(out, s[start:])
	return out
}
