package ged

import (
	"os"
	"path/filepath"
	"testing"
)

// TestGenerateDesignRefusesAForeignGeneratedFile guards a silent overwrite that
// destroys working code. silkide writes the same <stem>.silk.go name from a
// different generator — package ui with a BuildXxx() returning a decl.Node —
// and the designer's 全部生成 replaced it with its own struct, deleting the
// function the user's hand-written package-ui file calls, while reporting
// success.
func TestGenerateDesignRefusesAForeignGeneratedFile(t *testing.T) {
	dir := t.TempDir()
	design := filepath.Join(dir, "editor.silkui")
	writeMinimalDesign(t, design)

	foreign := filepath.Join(dir, "editor.silk.go")
	const body = `// Code generated by silkide — DO NOT EDIT.
// Source: editor.silkui

package ui

func BuildEditor() {}
`
	if err := os.WriteFile(foreign, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := GenerateDesign(design, "example.com/app"); err == nil {
		t.Error("the designer overwrote a file silkide owns; the user's BuildEditor call no longer compiles")
	}

	got, err := os.ReadFile(foreign)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != body {
		t.Errorf("the foreign generated file was modified:\n%s", got)
	}
}

// TestGenerateDesignWritesWhenItOwnsTheFile keeps the guard from refusing
// everything: a file this designer wrote before must still be regenerated.
func TestGenerateDesignWritesWhenItOwnsTheFile(t *testing.T) {
	dir := t.TempDir()
	design := filepath.Join(dir, "form.silkui")
	writeMinimalDesign(t, design)

	out, err := GenerateDesign(design, "example.com/app")
	if err != nil {
		t.Fatalf("first generation failed: %v", err)
	}
	if _, err := os.Stat(out); err != nil {
		t.Fatalf("nothing was written: %v", err)
	}
	if _, err := GenerateDesign(design, "example.com/app"); err != nil {
		t.Errorf("regenerating a file the designer owns was refused: %v", err)
	}
}

func writeMinimalDesign(t *testing.T, path string) {
	t.Helper()
	scene := NewGedScene()
	if err := scene.SaveDesign().SaveFile(path); err != nil {
		t.Fatalf("SaveDesign(%s): %v", path, err)
	}
}
