package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"silk/a11y"
	"silk/decl"
	"silk/ged"
	"silk/gui"
	"silk/i18n"
)

// TestSampleMainGoLooksLikeReference locks in the sample seed code so
// reviewers can compare it against the mockup image side-by-side. If
// the mock changes, this test will guide what to update in
// sampleMainGo and the screenshot.
func TestSampleMainGoLooksLikeReference(t *testing.T) {
	src := sampleMainGo()
	for _, want := range []string{
		"package main",
		`"fmt"`,
		`"net/http"`,
		"func main()",
		"http.HandleFunc",
		`"Server starting on :8080"`,
		"func handler",
		`"Hello, gogpu!"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("sampleMainGo missing %q\n----\n%s", want, src)
		}
	}
}

// TestSampleServerGoLooksLikeReference: server.go tab content matches
// the second tab shown in the mockup.
func TestSampleServerGoLooksLikeReference(t *testing.T) {
	src := sampleServerGo()
	for _, want := range []string{
		"package server",
		"type Server struct",
		"func New() *Server",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("sampleServerGo missing %q\n----\n%s", want, src)
		}
	}
}

// TestSampleGoModLooksLikeReference: go.mod tab content shape.
func TestSampleGoModLooksLikeReference(t *testing.T) {
	src := sampleGoMod()
	for _, want := range []string{
		"module github.com/user/myproject",
		"go 1.25",
		"require",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("sampleGoMod missing %q\n----\n%s", want, src)
		}
	}
}

// TestIDTitleFormat: title should be "<basename> — silkide" so the
// window chrome matches the mockup's "<project> — main.go" pattern.
func TestIDTitleFormat(t *testing.T) {
	got := idTitle()
	if !strings.Contains(got, " — silkide") {
		t.Errorf("idTitle() = %q; should contain ' — silkide' separator", got)
	}
}

// TestOpenFileInEditorReusesExistingTab: opening the same path
// twice should focus the existing tab rather than stack a duplicate.
// Without dedup, BuildOutput's click-to-jump would multiply tabs
// every time the user clicked an error in the same file.
func TestOpenFileInEditorReusesExistingTab(t *testing.T) {
	// Reset the package map between tests to keep them order-
	// independent.
	openEditors = map[string]*gui.CodeEditor{}

	tabs := gui.NewTabWidget()
	dir := t.TempDir()
	path := filepath.Join(dir, "hello.go")
	if err := os.WriteFile(path, []byte("package main\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if !openFileInEditor(tabs, path) {
		t.Fatal("first open returned false")
	}
	first := tabs.Count()

	if !openFileInEditor(tabs, path) {
		t.Fatal("second open returned false")
	}
	if tabs.Count() != first {
		t.Errorf("tab count grew on re-open: %d → %d (expected dedup)",
			first, tabs.Count())
	}
}

// TestHasMainPackageDetectsRunnable: a directory with a "package
// main" file is runnable; one without isn't. silkide's Run pre-
// flight uses this to swap the cryptic "package . is not a main
// package" error for a friendly message pointing the user at
// silkide's File→New.
func TestHasMainPackageDetectsRunnable(t *testing.T) {
	dir := t.TempDir()

	// Empty directory → not runnable.
	if hasMainPackage(dir) {
		t.Errorf("empty dir reported runnable")
	}

	// Library-only file → not runnable.
	libPath := filepath.Join(dir, "lib.go")
	if err := os.WriteFile(libPath, []byte("// header comment\n\npackage ui\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if hasMainPackage(dir) {
		t.Errorf("lib-only dir reported runnable")
	}

	// Add a main.go and re-check.
	mainPath := filepath.Join(dir, "main.go")
	if err := os.WriteFile(mainPath, []byte("package main\n\nfunc main() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !hasMainPackage(dir) {
		t.Errorf("dir with main.go not reported runnable")
	}

	// _test.go files should be ignored by the scan.
	testPath := filepath.Join(dir, "x_test.go")
	if err := os.WriteFile(testPath, []byte("package ui\n\nfunc TestX(t *testing.T) {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !hasMainPackage(dir) {
		t.Errorf("_test.go shouldn't have flipped runnable=false")
	}
}

// TestFirstPackageLineIsMainSkipsCommentsAndBlanks: the package-
// directive scan must walk past leading // comments and blank
// lines so "// Code generated by …\n\npackage main" still
// resolves to runnable.
func TestFirstPackageLineIsMainSkipsCommentsAndBlanks(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{"plain main", "package main\n", true},
		{"comment then main", "// hello\npackage main\n", true},
		{"blank then main", "\n\npackage main\n", true},
		{"library", "package ui\n", false},
		{"comment then library", "// hi\npackage ui\n", false},
		{"empty", "", false},
		{"just comments", "// foo\n// bar\n", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := firstPackageLineIsMain(c.src); got != c.want {
				t.Errorf("got %v, want %v\n%s", got, c.want, c.src)
			}
		})
	}
}

// TestProjectDirResolvesFromActiveScene: a canvas with a scene whose
// filename points at /tmp/work/Editor.silkui resolves to /tmp/work.
// Falling back to os.Getwd happens only when the scene has no path,
// so the resolver behaves like JetBrains' "run in module of the
// active editor" rule.
func TestProjectDirResolvesFromActiveScene(t *testing.T) {
	view := ged.NewGedView()
	scene := view.GedScene()

	// Empty filename → falls back to process cwd.
	got := projectDir(view)
	wantCwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if got != wantCwd {
		t.Errorf("empty-filename canvas: projectDir = %q, want %q", got, wantCwd)
	}

	scene.SetFilename("/tmp/work/Editor.silkui")
	if got = projectDir(view); got != "/tmp/work" {
		t.Errorf("with filename: projectDir = %q, want %q", got, "/tmp/work")
	}

	if got = projectDir(nil); got != wantCwd {
		t.Errorf("nil canvas: projectDir = %q, want %q (cwd fallback)", got, wantCwd)
	}
}

// TestConfirmDiscardDirtyAllowsCleanScene: a clean scene short-
// circuits the dialog and returns true, so File→New / Open / Quit
// don't pester the user when there's nothing to lose. The dirty
// branch is exercised manually since it requires a modal window.
func TestConfirmDiscardDirtyAllowsCleanScene(t *testing.T) {
	if got := confirmDiscardDirty(nil); !got {
		t.Errorf("nil canvas: got false, want true (no work to lose)")
	}

	view := ged.NewGedView()
	if !confirmDiscardDirty(view) {
		t.Errorf("fresh canvas: got false, want true (no dirty state)")
	}

	// Mark the scene dirty by pushing a real command; the helper
	// must NOT short-circuit through the clean-scene branch when
	// this happens. We can't drive the modal here, so just verify
	// the precondition flips.
	scene := view.GedScene()
	stack := scene.UndoStack()
	if stack == nil {
		t.Fatal("scene has no undo stack")
	}
	if !stack.IsClean() {
		t.Fatal("expected clean stack before mutation")
	}
	scene.SetSize(10, 10)
	// SceneItem.SetSize doesn't push a command on its own — we need
	// to fabricate dirtiness for the precondition check. Use a real
	// MoveCommand-equivalent via a fake widget.
	fake, err := ged.NewFakeWidgetFromFactory("gui.Button")
	if err != nil {
		t.Fatalf("create fake: %v", err)
	}
	fake.SetParent(scene)
	view.Selection().Add(fake)
	cmd := view.Selection().GenerateMoveCommand(5, 5)
	if cmd == nil {
		t.Fatal("expected non-nil MoveCommand")
	}
	stack.Push(cmd)
	if stack.IsClean() {
		t.Errorf("stack should be dirty after Push; helper would short-circuit incorrectly")
	}
}

// TestItemBoundsLabelFormatsRect: status-bar bounds cell shape
// "(x, y) w×h" with integer-rounded values. Drives the formatting
// helper directly so the wiring in the SelectionCallback can
// trust the format string.
func TestItemBoundsLabelFormatsRect(t *testing.T) {
	if got := itemBoundsLabel(nil); got != "" {
		t.Errorf("nil item: got %q, want empty string", got)
	}

	view := ged.NewGedView()
	scene := view.GedScene()
	fake, err := ged.NewFakeWidgetFromFactory("gui.Button")
	if err != nil {
		t.Fatalf("create fake: %v", err)
	}
	fake.SetParent(scene)
	fake.SetPos(10, 20)
	fake.SetSize(80, 40)

	if got := itemBoundsLabel(fake); got != "(10, 20) 80×40" {
		t.Errorf("itemBoundsLabel = %q, want %q", got, "(10, 20) 80×40")
	}
}

// TestExportDesignCanvasSVG drives the export wiring without the
// SaveFileDialog: build a fresh GedView, hand exportDesignCanvas a
// .svg path inside t.TempDir, and confirm the file ends up with the
// SVG XML preamble. Locks in the toolbar's "preview" action contract
// against accidental dispatch regressions.
func TestExportDesignCanvasSVG(t *testing.T) {
	view := ged.NewGedView()
	tmp := filepath.Join(t.TempDir(), "scene.svg")
	if err := exportDesignCanvas(tmp, view); err != nil {
		t.Fatalf("exportDesignCanvas: %v", err)
	}
	data, err := os.ReadFile(tmp)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "<?xml") {
		t.Fatalf("svg output missing XML preamble: %q", string(data[:min(80, len(data))]))
	}
	if !strings.Contains(string(data), "<svg") {
		t.Errorf("svg output missing <svg> root")
	}
}

// TestExportDesignCanvasPDF: same shape, .pdf path → PDFPainter →
// %PDF header.
func TestExportDesignCanvasPDF(t *testing.T) {
	view := ged.NewGedView()
	tmp := filepath.Join(t.TempDir(), "scene.pdf")
	if err := exportDesignCanvas(tmp, view); err != nil {
		t.Fatalf("exportDesignCanvas: %v", err)
	}
	data, err := os.ReadFile(tmp)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "%PDF-") {
		t.Fatalf("pdf output missing %%PDF- header: %q", string(data[:min(80, len(data))]))
	}
}

// TestRegenerateGoForSilkui: writes a sibling .silk.go for a saved
// .silkui. Stem-derived function name + standard "package ui" header
// + "Code generated by silkide" provenance line. Exercises the
// in-IDE silkgen pipeline without spawning the cmd/silkgen binary.
//
// Uses decl.Form(..) → ToTDoc → SaveFile to lay down a real .silkui
// fixture; constructing the TDoc text by hand would be brittle to
// formatting changes in core's TDoc serialiser.
func TestRegenerateGoForSilkui(t *testing.T) {
	dir := t.TempDir()
	silkui := filepath.Join(dir, "Editor.silkui")

	// Build a tiny valid decl tree and save it the same way GedScene
	// would. Minimal Form with one Button child — enough to exercise
	// the FromTDoc / ToGo path end-to-end.
	tree := decl.Form(
		decl.ID("Root"),
		decl.P("title", "Editor"),
		decl.Child(decl.Button(decl.ID("ok"), decl.P("text", "OK"))),
	)
	doc := decl.ToTDoc(tree)
	if err := doc.SaveFile(silkui); err != nil {
		t.Fatalf("save fixture: %v", err)
	}

	regenerateGoForSilkui(silkui)

	out := filepath.Join(dir, "Editor.silk.go")
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("expected %q to exist: %v", out, err)
	}
	for _, want := range []string{
		"// Code generated by silkide — DO NOT EDIT.",
		"package ui",
		`import "silk/decl"`,
		"func BuildEditor() *decl.Node",
	} {
		if !strings.Contains(string(data), want) {
			t.Errorf(".silk.go missing %q\n----\n%s", want, string(data))
		}
	}
}

// TestExportDesignCanvasUnknownExtension: paths without a recognised
// extension default to SVG and the output filename gets ".svg"
// appended so the saved file is recognisable.
func TestExportDesignCanvasUnknownExtension(t *testing.T) {
	view := ged.NewGedView()
	base := filepath.Join(t.TempDir(), "scene")
	if err := exportDesignCanvas(base, view); err != nil {
		t.Fatalf("exportDesignCanvas: %v", err)
	}
	want := base + ".svg"
	if _, err := os.Stat(want); err != nil {
		t.Fatalf("expected %q to exist: %v", want, err)
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// TestRegisterSilkideTranslations: zh-CN translations registered by
// installLocale must include the toolbar / menu strings silkide
// actually emits, otherwise switching to a Chinese locale leaves
// English labels showing.
func TestRegisterSilkideTranslations(t *testing.T) {
	registerSilkideTranslations()
	prev := i18n.Locale()
	defer i18n.SetLocale(prev)

	i18n.SetLocale("zh-CN")
	cases := map[string]string{
		"Debug":  "调试",
		"Save":   "保存",
		"Open":   "打开",
		"Undo":   "撤销",
		"Redo":   "重做",
		"Settings": "设置",
	}
	for src, want := range cases {
		got := i18n.T(src)
		if got != want {
			t.Errorf("Tr(%q) = %q, want %q", src, got, want)
		}
	}
}

// TestDumpA11yNodeFormatsTree: the indented-tree formatter handles
// a representative root → children shape and produces a stable
// stderr-shape that future bug reports can diff against.
func TestDumpA11yNodeFormatsTree(t *testing.T) {
	// Capture stderr.
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	saved := os.Stderr
	os.Stderr = w
	defer func() { os.Stderr = saved }()

	tree := &a11y.Node{
		Role: a11y.RoleWindow,
		Name: "silkide",
		Children: []*a11y.Node{
			{Role: a11y.RoleToolBar, Name: "tools"},
			{Role: a11y.RoleButton, Name: "Save"},
		},
	}
	dumpA11yNode(tree, 0)
	w.Close()

	buf := make([]byte, 1024)
	n, _ := r.Read(buf)
	got := string(buf[:n])

	for _, want := range []string{
		"Window silkide",
		"  ToolBar tools",
		"  Button Save",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("dumpA11yNode missing %q\n----\n%s", want, got)
		}
	}
}

// TestRecentFilesRoundTrip exercises AddRecentFile / RecentFiles:
// MRU ordering, de-dup, capped length, missing-file filtering.
func TestRecentFilesRoundTrip(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", tmp)
	t.Setenv("HOME", tmp)

	// Create three real files so RecentFiles' stat filter accepts them.
	paths := []string{
		filepath.Join(tmp, "a.txt"),
		filepath.Join(tmp, "b.txt"),
		filepath.Join(tmp, "c.txt"),
	}
	for _, p := range paths {
		if err := os.WriteFile(p, []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	p := newPreferences()

	// Push in order a → b → c. Front-of-list is c, then b, then a.
	for _, path := range paths {
		p.AddRecentFile(path)
	}
	got := p.RecentFiles()
	if len(got) != 3 {
		t.Fatalf("after 3 distinct adds: got %d entries, want 3", len(got))
	}
	if got[0] != paths[2] || got[2] != paths[0] {
		t.Errorf("MRU order broken: %v\n want [c, b, a]", got)
	}

	// Re-add 'a' — moves to front, doesn't dup.
	p.AddRecentFile(paths[0])
	got = p.RecentFiles()
	if len(got) != 3 {
		t.Errorf("after dup-readd: %d entries, want 3", len(got))
	}
	if got[0] != paths[0] {
		t.Errorf("re-add didn't move to front: %v", got)
	}

	// Delete a file on disk. Its entry stays in the underlying list
	// but RecentFiles filters it out.
	if err := os.Remove(paths[1]); err != nil {
		t.Fatal(err)
	}
	got = p.RecentFiles()
	for _, g := range got {
		if g == paths[1] {
			t.Errorf("deleted file %q still in RecentFiles", paths[1])
		}
	}
}

// TestPreferencesWindowSize: prefs.WindowSize round-trips through
// SetWindowSize, and the default falls back to a sane non-zero value
// when the settings file is empty.
func TestPreferencesWindowSize(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", tmp) // Linux fallback path
	t.Setenv("HOME", tmp)            // macOS Application Support path

	p := newPreferences()
	w, h := p.WindowSize()
	if w < 320 || h < 240 {
		t.Errorf("default WindowSize = (%d, %d), expected ≥ (320, 240)", w, h)
	}

	p.SetWindowSize(1500, 950)
	p2 := newPreferences()
	if w2, h2 := p2.WindowSize(); w2 != 1500 || h2 != 950 {
		t.Errorf("after SetWindowSize(1500, 950): WindowSize() = (%d, %d)", w2, h2)
	}
}
