package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"silk/a11y"
	"silk/decl"
	"silk/ged"
	"silk/i18n"
)

// TestSampleMainGoLooksLikeReference locks in the sample seed code so
// reviewers can compare it against the mockup image side-by-side. If
// the mock changes, this test will guide what to update in
// sampleMainGo and the screenshot.
func TestSampleMainGoLooksLikeReference(t *testing.T) {
	src := sampleMainGo()
	for _, want := range []string{
		"package main",
		`"fmt"`,
		`"net/http"`,
		"func main()",
		"http.HandleFunc",
		`"Server starting on :8080"`,
		"func handler",
		`"Hello, gogpu!"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("sampleMainGo missing %q\n----\n%s", want, src)
		}
	}
}

// TestSampleServerGoLooksLikeReference: server.go tab content matches
// the second tab shown in the mockup.
func TestSampleServerGoLooksLikeReference(t *testing.T) {
	src := sampleServerGo()
	for _, want := range []string{
		"package server",
		"type Server struct",
		"func New() *Server",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("sampleServerGo missing %q\n----\n%s", want, src)
		}
	}
}

// TestSampleGoModLooksLikeReference: go.mod tab content shape.
func TestSampleGoModLooksLikeReference(t *testing.T) {
	src := sampleGoMod()
	for _, want := range []string{
		"module github.com/user/myproject",
		"go 1.25",
		"require",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("sampleGoMod missing %q\n----\n%s", want, src)
		}
	}
}

// TestIDTitleFormat: title should be "<basename> — silkide" so the
// window chrome matches the mockup's "<project> — main.go" pattern.
func TestIDTitleFormat(t *testing.T) {
	got := idTitle()
	if !strings.Contains(got, " — silkide") {
		t.Errorf("idTitle() = %q; should contain ' — silkide' separator", got)
	}
}

// TestExportDesignCanvasSVG drives the export wiring without the
// SaveFileDialog: build a fresh GedView, hand exportDesignCanvas a
// .svg path inside t.TempDir, and confirm the file ends up with the
// SVG XML preamble. Locks in the toolbar's "preview" action contract
// against accidental dispatch regressions.
func TestExportDesignCanvasSVG(t *testing.T) {
	view := ged.NewGedView()
	tmp := filepath.Join(t.TempDir(), "scene.svg")
	if err := exportDesignCanvas(tmp, view); err != nil {
		t.Fatalf("exportDesignCanvas: %v", err)
	}
	data, err := os.ReadFile(tmp)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "<?xml") {
		t.Fatalf("svg output missing XML preamble: %q", string(data[:min(80, len(data))]))
	}
	if !strings.Contains(string(data), "<svg") {
		t.Errorf("svg output missing <svg> root")
	}
}

// TestExportDesignCanvasPDF: same shape, .pdf path → PDFPainter →
// %PDF header.
func TestExportDesignCanvasPDF(t *testing.T) {
	view := ged.NewGedView()
	tmp := filepath.Join(t.TempDir(), "scene.pdf")
	if err := exportDesignCanvas(tmp, view); err != nil {
		t.Fatalf("exportDesignCanvas: %v", err)
	}
	data, err := os.ReadFile(tmp)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "%PDF-") {
		t.Fatalf("pdf output missing %%PDF- header: %q", string(data[:min(80, len(data))]))
	}
}

// TestRegenerateGoForSilkui: writes a sibling .silk.go for a saved
// .silkui. Stem-derived function name + standard "package ui" header
// + "Code generated by silkide" provenance line. Exercises the
// in-IDE silkgen pipeline without spawning the cmd/silkgen binary.
//
// Uses decl.Form(..) → ToTDoc → SaveFile to lay down a real .silkui
// fixture; constructing the TDoc text by hand would be brittle to
// formatting changes in core's TDoc serialiser.
func TestRegenerateGoForSilkui(t *testing.T) {
	dir := t.TempDir()
	silkui := filepath.Join(dir, "Editor.silkui")

	// Build a tiny valid decl tree and save it the same way GedScene
	// would. Minimal Form with one Button child — enough to exercise
	// the FromTDoc / ToGo path end-to-end.
	tree := decl.Form(
		decl.ID("Root"),
		decl.P("title", "Editor"),
		decl.Child(decl.Button(decl.ID("ok"), decl.P("text", "OK"))),
	)
	doc := decl.ToTDoc(tree)
	if err := doc.SaveFile(silkui); err != nil {
		t.Fatalf("save fixture: %v", err)
	}

	regenerateGoForSilkui(silkui)

	out := filepath.Join(dir, "Editor.silk.go")
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("expected %q to exist: %v", out, err)
	}
	for _, want := range []string{
		"// Code generated by silkide — DO NOT EDIT.",
		"package ui",
		`import "silk/decl"`,
		"func BuildEditor() *decl.Node",
	} {
		if !strings.Contains(string(data), want) {
			t.Errorf(".silk.go missing %q\n----\n%s", want, string(data))
		}
	}
}

// TestExportDesignCanvasUnknownExtension: paths without a recognised
// extension default to SVG and the output filename gets ".svg"
// appended so the saved file is recognisable.
func TestExportDesignCanvasUnknownExtension(t *testing.T) {
	view := ged.NewGedView()
	base := filepath.Join(t.TempDir(), "scene")
	if err := exportDesignCanvas(base, view); err != nil {
		t.Fatalf("exportDesignCanvas: %v", err)
	}
	want := base + ".svg"
	if _, err := os.Stat(want); err != nil {
		t.Fatalf("expected %q to exist: %v", want, err)
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// TestRegisterSilkideTranslations: zh-CN translations registered by
// installLocale must include the toolbar / menu strings silkide
// actually emits, otherwise switching to a Chinese locale leaves
// English labels showing.
func TestRegisterSilkideTranslations(t *testing.T) {
	registerSilkideTranslations()
	prev := i18n.Locale()
	defer i18n.SetLocale(prev)

	i18n.SetLocale("zh-CN")
	cases := map[string]string{
		"Debug":  "调试",
		"Save":   "保存",
		"Open":   "打开",
		"Undo":   "撤销",
		"Redo":   "重做",
		"Settings": "设置",
	}
	for src, want := range cases {
		got := i18n.T(src)
		if got != want {
			t.Errorf("Tr(%q) = %q, want %q", src, got, want)
		}
	}
}

// TestDumpA11yNodeFormatsTree: the indented-tree formatter handles
// a representative root → children shape and produces a stable
// stderr-shape that future bug reports can diff against.
func TestDumpA11yNodeFormatsTree(t *testing.T) {
	// Capture stderr.
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	saved := os.Stderr
	os.Stderr = w
	defer func() { os.Stderr = saved }()

	tree := &a11y.Node{
		Role: a11y.RoleWindow,
		Name: "silkide",
		Children: []*a11y.Node{
			{Role: a11y.RoleToolBar, Name: "tools"},
			{Role: a11y.RoleButton, Name: "Save"},
		},
	}
	dumpA11yNode(tree, 0)
	w.Close()

	buf := make([]byte, 1024)
	n, _ := r.Read(buf)
	got := string(buf[:n])

	for _, want := range []string{
		"Window silkide",
		"  ToolBar tools",
		"  Button Save",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("dumpA11yNode missing %q\n----\n%s", want, got)
		}
	}
}

// TestRecentFilesRoundTrip exercises AddRecentFile / RecentFiles:
// MRU ordering, de-dup, capped length, missing-file filtering.
func TestRecentFilesRoundTrip(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", tmp)
	t.Setenv("HOME", tmp)

	// Create three real files so RecentFiles' stat filter accepts them.
	paths := []string{
		filepath.Join(tmp, "a.txt"),
		filepath.Join(tmp, "b.txt"),
		filepath.Join(tmp, "c.txt"),
	}
	for _, p := range paths {
		if err := os.WriteFile(p, []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	p := newPreferences()

	// Push in order a → b → c. Front-of-list is c, then b, then a.
	for _, path := range paths {
		p.AddRecentFile(path)
	}
	got := p.RecentFiles()
	if len(got) != 3 {
		t.Fatalf("after 3 distinct adds: got %d entries, want 3", len(got))
	}
	if got[0] != paths[2] || got[2] != paths[0] {
		t.Errorf("MRU order broken: %v\n want [c, b, a]", got)
	}

	// Re-add 'a' — moves to front, doesn't dup.
	p.AddRecentFile(paths[0])
	got = p.RecentFiles()
	if len(got) != 3 {
		t.Errorf("after dup-readd: %d entries, want 3", len(got))
	}
	if got[0] != paths[0] {
		t.Errorf("re-add didn't move to front: %v", got)
	}

	// Delete a file on disk. Its entry stays in the underlying list
	// but RecentFiles filters it out.
	if err := os.Remove(paths[1]); err != nil {
		t.Fatal(err)
	}
	got = p.RecentFiles()
	for _, g := range got {
		if g == paths[1] {
			t.Errorf("deleted file %q still in RecentFiles", paths[1])
		}
	}
}

// TestPreferencesWindowSize: prefs.WindowSize round-trips through
// SetWindowSize, and the default falls back to a sane non-zero value
// when the settings file is empty.
func TestPreferencesWindowSize(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", tmp) // Linux fallback path
	t.Setenv("HOME", tmp)            // macOS Application Support path

	p := newPreferences()
	w, h := p.WindowSize()
	if w < 320 || h < 240 {
		t.Errorf("default WindowSize = (%d, %d), expected ≥ (320, 240)", w, h)
	}

	p.SetWindowSize(1500, 950)
	p2 := newPreferences()
	if w2, h2 := p2.WindowSize(); w2 != 1500 || h2 != 950 {
		t.Errorf("after SetWindowSize(1500, 950): WindowSize() = (%d, %d)", w2, h2)
	}
}
